image: java:8

before_script:
    - chmod +x mvnw

after_script:
    - ls target

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: ./mvnw clean install
  artifacts:
    paths:
        - target/spring-boot-backend-api-rest-0.0.1-SNAPSHOT.jar

test_sonar:
  stage: test
 except:
    - master
    - tags
  script:
    - ./mvnw --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar -Dsonar.host.url=$SONAR_OFF_URL -Dsonar.login=$SONAR_OFF_LOGIN -Dsonar.branch.name=$CI_COMMIT_REF_NAME
  tags:
    - docker

production:
  stage: deploy
  script:
  - cd target
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io -o afore-xxi-core.org -s development
  - ./cf push afore-xxi-core-demo2 -m 1G -p spring-boot-backend-api-rest-0.0.1-SNAPSHOT.jar -b java_buildpack
  only:
  - master
  