image: java:8

before_script:
    - chmod +x mvnw
    - echo $CI_BUILD_REF
    - echo $CI_PROJECT_DIR
    - mkdir $CI_PROJECT_DIR/target
    - ls $CI_PROJECT_DIR/target

stages:
  - build
  - deploy

build:
  stage: build
  script: ./mvnw clean package install

production:
  stage: deploy
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io -o afore-xxi-core.org -s development
  - ./cf push app-afore-xxi-core -b java_buildpack
  only:
  - master
  