image: java:8

variables:
  SONAR_URL: "http://localhost:9000"
  SONAR_LOGIN: "admin"
  SONAR_PASSWORD: "admin"


before_script:
    - chmod +x mvnw
    
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/afore-xxi-demo-0.0.1-SNAPSHOT.jar

sonarqube_master_job:
  stage: test
  only:
    - master
  image: maven:3.3.9-jdk-8-alpine
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD
    
production:
  stage: deploy
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf push
  only:
  - master