image: java:8

before_script:
    - chmod +x mvnw
    
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/afore-xxi-demo-0.0.1-SNAPSHOT.jar

sonarqube_master_job:
  stage: test
  only:
    - master
  script:
    - ./mvnw --batch-mode verify sonar:sonar -Dsonar.host.url=http://local.sonarqube.com:9000 -Dsonar.login=admin -Dsonar.password=admin

production:
  stage: deploy
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf push
  only:
  - master