image: java:8

before_script:
    - chmod +x mvnw

after_script:
    - ls target

stages:
  - build
  - deploy

build:
  stage: build
  script: ./mvnw clean install
  artifacts:
    paths:
        - target/spring-boot-backend-api-rest-0.0.1-SNAPSHOT.jar
  
production:
  stage: deploy
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io -o afore-xxi-core.org -s development
  - ./cf push spring-boot-backend-api-rest-0.0.1-SNAPSHOT -b java_buildpack
  only:
  - master
  