image: java:8

before_script:
    - chmod +x mvnw
    
stages:
  - build
  - deploy
  
build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/afore-xxi-demo-0.0.1-SNAPSHOT.jar

production:
  stage: deploy
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf target -o ORG -s SPACE login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
  - ./cf push
  only:
  - master
  