image: java:8

variables:
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - .m2/repository

before_script:
    - chmod +x mvnw
    
stages:
  - build
  - deploy
  
build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/afore-xxi-demo-0.0.1-SNAPSHOT.jar

sonar:
  stage: sonar
  script:
    - ./mvnw $MAVEN_CLI_OPTS sonar:sonar
    
production:
  stage: deploy
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
  - ./cf push
  only:
  - master
  